
import type { Deck, Card, GrammarPoint, QuizMeta, ListeningQuizQuestion, CreativeChallenge, GrammarPointExample } from './types';

export const basicDecks: Deck[] = [
  {
    id: 'hiragana',
    name: 'Hiragana Basics',
    description: 'Master the fundamental Japanese syllabary.',
    cardCount: 46,
    isCustom: false,
  },
  {
    id: 'katakana',
    name: 'Katakana Practice',
    description: 'Learn the script used for foreign words.',
    cardCount: 46,
    isCustom: false,
  },
  {
    id: 'n5-vocab',
    name: 'JLPT N5 Vocabulary',
    description: 'Essential words for beginner proficiency.',
    cardCount: 100,
    isCustom: false,
  },
   {
    id: 'n4-vocab',
    name: 'JLPT N4 Vocabulary',
    description: 'Intermediate words for expanding your vocabulary.',
    cardCount: 150,
    isCustom: false,
  },
  {
    id: 'n3-vocab',
    name: 'JLPT N3 Vocabulary',
    description: 'Upper-intermediate words.',
    cardCount: 5,
    isCustom: false,
  },
  {
    id: 'n2-vocab',
    name: 'JLPT N2 Vocabulary',
    description: 'Pre-advanced vocabulary.',
    cardCount: 5,
    isCustom: false,
  },
  {
    id: 'n1-vocab',
    name: 'JLPT N1 Vocabulary',
    description: 'Advanced and specialized words.',
    cardCount: 5,
    isCustom: false,
  },
];

export const cards: Card[] = [
  // Hiragana (46 cards)
  { id: 'h-1', deckId: 'hiragana', front: 'あ', back: 'a' },
  { id: 'h-2', deckId: 'hiragana', front: 'い', back: 'i' },
  { id: 'h-3', deckId: 'hiragana', front: 'う', back: 'u' },
  { id: 'h-4', deckId: 'hiragana', front: 'え', back: 'e' },
  { id: 'h-5', deckId: 'hiragana', front: 'お', back: 'o' },
  { id: 'h-6', deckId: 'hiragana', front: 'か', back: 'ka' },
  { id: 'h-7', deckId: 'hiragana', front: 'き', back: 'ki' },
  { id: 'h-8', deckId: 'hiragana', front: 'く', back: 'ku' },
  { id: 'h-9', deckId: 'hiragana', front: 'け', back: 'ke' },
  { id: 'h-10', deckId: 'hiragana', front: 'こ', back: 'ko' },
  { id: 'h-11', deckId: 'hiragana', front: 'さ', back: 'sa' },
  { id: 'h-12', deckId: 'hiragana', front: 'し', back: 'shi' },
  { id: 'h-13', deckId: 'hiragana', front: 'す', back: 'su' },
  { id: 'h-14', deckId: 'hiragana', front: 'せ', back: 'se' },
  { id: 'h-15', deckId: 'hiragana', front: 'そ', back: 'so' },
  { id: 'h-16', deckId: 'hiragana', front: 'た', back: 'ta' },
  { id: 'h-17', deckId: 'hiragana', front: 'ち', back: 'chi' },
  { id: 'h-18', deckId: 'hiragana', front: 'つ', back: 'tsu' },
  { id: 'h-19', deckId: 'hiragana', front: 'て', back: 'te' },
  { id: 'h-20', deckId: 'hiragana', front: 'と', back: 'to' },
  { id: 'h-21', deckId: 'hiragana', front: 'な', back: 'na' },
  { id: 'h-22', deckId: 'hiragana', front: 'に', back: 'ni' },
  { id: 'h-23', deckId: 'hiragana', front: 'ぬ', back: 'nu' },
  { id: 'h-24', deckId: 'hiragana', front: 'ね', back: 'ne' },
  { id: 'h-25', deckId: 'hiragana', front: 'の', back: 'no' },
  { id: 'h-26', deckId: 'hiragana', front: 'は', back: 'ha' },
  { id: 'h-27', deckId: 'hiragana', front: 'ひ', back: 'hi' },
  { id: 'h-28', deckId: 'hiragana', front: 'ふ', back: 'fu' },
  { id: 'h-29', deckId: 'hiragana', front: 'へ', back: 'he' },
  { id: 'h-30', deckId: 'hiragana', front: 'ほ', back: 'ho' },
  { id: 'h-31', deckId: 'hiragana', front: 'ま', back: 'ma' },
  { id: 'h-32', deckId: 'hiragana', front: 'み', back: 'mi' },
  { id: 'h-33', deckId: 'hiragana', front: 'む', back: 'mu' },
  { id: 'h-34', deckId: 'hiragana', front: 'め', back: 'me' },
  { id: 'h-35', deckId: 'hiragana', front: 'も', back: 'mo' },
  { id: 'h-36', deckId: 'hiragana', front: 'や', back: 'ya' },
  { id: 'h-37', deckId: 'hiragana', front: 'ゆ', back: 'yu' },
  { id: 'h-38', deckId: 'hiragana', front: 'よ', back: 'yo' },
  { id: 'h-39', deckId: 'hiragana', front: 'ら', back: 'ra' },
  { id: 'h-40', deckId: 'hiragana', front: 'り', back: 'ri' },
  { id: 'h-41', deckId: 'hiragana', front: 'る', back: 'ru' },
  { id: 'h-42', deckId: 'hiragana', front: 'れ', back: 're' },
  { id: 'h-43', deckId: 'hiragana', front: 'ろ', back: 'ro' },
  { id: 'h-44', deckId: 'hiragana', front: 'わ', back: 'wa' },
  { id: 'h-45', deckId: 'hiragana', front: 'を', back: 'wo' },
  { id: 'h-46', deckId: 'hiragana', front: 'ん', back: 'n' },

  // Katakana (46 cards)
  { id: 'k-1', deckId: 'katakana', front: 'ア', back: 'a' },
  { id: 'k-2', deckId: 'katakana', front: 'イ', back: 'i' },
  { id: 'k-3', deckId: 'katakana', front: 'ウ', back: 'u' },
  { id: 'k-4', deckId: 'katakana', front: 'エ', back: 'e' },
  { id: 'k-5', deckId: 'katakana', front: 'オ', back: 'o' },
  { id: 'k-6', deckId: 'katakana', front: 'カ', back: 'ka' },
  { id: 'k-7', deckId: 'katakana', front: 'キ', back: 'ki' },
  { id: 'k-8', deckId: 'katakana', front: 'ク', back: 'ku' },
  { id: 'k-9', deckId: 'katakana', front: 'ケ', back: 'ke' },
  { id: 'k-10', deckId: 'katakana', front: 'コ', back: 'ko' },
  { id: 'k-11', deckId: 'katakana', front: 'サ', back: 'sa' },
  { id: 'k-12', deckId: 'katakana', front: 'シ', back: 'shi' },
  { id: 'k-13', deckId: 'katakana', front: 'ス', back: 'su' },
  { id: 'k-14', deckId: 'katakana', front: 'セ', back: 'se' },
  { id: 'k-15', deckId: 'katakana', front: 'ソ', back: 'so' },
  { id: 'k-16', deckId: 'katakana', front: 'タ', back: 'ta' },
  { id: 'k-17', deckId: 'katakana', front: 'チ', back: 'chi' },
  { id: 'k-18', deckId: 'katakana', front: 'ツ', back: 'tsu' },
  { id: 'k-19', deckId: 'katakana', front: 'テ', back: 'te' },
  { id: 'k-20', deckId: 'katakana', front: 'ト', back: 'to' },
  { id: 'k-21', deckId: 'katakana', front: 'ナ', back: 'na' },
  { id: 'k-22', deckId: 'katakana', front: 'ニ', back: 'ni' },
  { id: 'k-23', deckId: 'katakana', front: 'ヌ', back: 'nu' },
  { id: 'k-24', deckId: 'katakana', front: 'ネ', back: 'ne' },
  { id: 'k-25', deckId: 'katakana', front: 'ノ', back: 'no' },
  { id: 'k-26', deckId: 'katakana', front: 'ハ', back: 'ha' },
  { id: 'k-27', deckId: 'katakana', front: 'ヒ', back: 'hi' },
  { id: 'k-28', deckId: 'katakana', front: 'フ', back: 'fu' },
  { id: 'k-29', deckId: 'katakana', front: 'ヘ', back: 'he' },
  { id: 'k-30', deckId: 'katakana', front: 'ホ', back: 'ho' },
  { id: 'k-31', deckId: 'katakana', front: 'マ', back: 'ma' },
  { id: 'k-32', deckId: 'katakana', front: 'ミ', back: 'mi' },
  { id: 'k-33', deckId: 'katakana', front: 'ム', back: 'mu' },
  { id: 'k-34', deckId: 'katakana', front: 'メ', back: 'me' },
  { id: 'k-35', deckId: 'katakana', front: 'モ', back: 'mo' },
  { id: 'k-36', deckId: 'katakana', front: 'ヤ', back: 'ya' },
  { id: 'k-37', deckId: 'katakana', front: 'ユ', back: 'yu' },
  { id: 'k-38', deckId: 'katakana', front: 'ヨ', back: 'yo' },
  { id: 'k-39', deckId: 'katakana', front: 'ラ', back: 'ra' },
  { id: 'k-40', deckId: 'katakana', front: 'リ', back: 'ri' },
  { id: 'k-41', deckId: 'katakana', front: 'ル', back: 'ru' },
  { id: 'k-42', deckId: 'katakana', front: 'レ', back: 're' },
  { id: 'k-43', deckId: 'katakana', front: 'ロ', back: 'ro' },
  { id: 'k-44', deckId: 'katakana', front: 'ワ', back: 'wa' },
  { id: 'k-45', deckId: 'katakana', front: 'ヲ', back: 'wo' },
  { id: 'k-46', deckId: 'katakana', front: 'ン', back: 'n' },

  // N5 Vocab (100 cards)
  { id: 'v-1', deckId: 'n5-vocab', front: '学校', back: 'School (gakkou)' },
  { id: 'v-2', deckId: 'n5-vocab', front: '先生', back: 'Teacher (sensei)' },
  { id: 'v-3', deckId: 'n5-vocab', front: '学生', back: 'Student (gakusei)' },
  { id: 'v-4', deckId: 'n5-vocab', front: '私', back: 'I, me (watashi)' },
  { id: 'v-5', deckId: 'n5-vocab', front: 'あなた', back: 'You (anata)' },
  { id: 'v-6', deckId: 'n5-vocab', front: '友達', back: 'Friend (tomodachi)' },
  { id: 'v-7', deckId: 'n5-vocab', front: '本', back: 'Book (hon)' },
  { id: 'v-8', deckId: 'n5-vocab', front: '机', back: 'Desk (tsukue)' },
  { id: 'v-9', deckId: 'n5-vocab', front: '椅子', back: 'Chair (isu)' },
  { id: 'v-10', deckId: 'n5-vocab', front: '犬', back: 'Dog (inu)' },
  { id: 'v-11', deckId: 'n5-vocab', front: '猫', back: 'Cat (neko)' },
  { id: 'v-12', deckId: 'n5-vocab', front: '食べる', back: 'To eat (taberu)' },
  { id: 'v-13', deckId: 'n5-vocab', front: '飲む', back: 'To drink (nomu)' },
  { id: 'v-14', deckId: 'n5-vocab', front: '見る', back: 'To see, to watch (miru)' },
  { id: 'v-15', deckId: 'n5-vocab', front: '聞く', back: 'To listen, to hear (kiku)' },
  { id: 'v-16', deckId: 'n5-vocab', front: '話す', back: 'To speak (hanasu)' },
  { id: 'v-17', deckId: 'n5-vocab', front: '行く', back: 'To go (iku)' },
  { id: 'v-18', deckId: 'n5-vocab', front: '来る', back: 'To come (kuru)' },
  { id: 'v-19', deckId: 'n5-vocab', front: '帰る', back: 'To return home (kaeru)' },
  { id: 'v-20', deckId: 'n5-vocab', front: '大きい', back: 'Big (ookii)' },
  { id: 'v-21', deckId: 'n5-vocab', front: '小さい', back: 'Small (chiisai)' },
  { id: 'v-22', deckId: 'n5-vocab', front: '高い', back: 'Tall, expensive (takai)' },
  { id: 'v-23', deckId: 'n5-vocab', front: '安い', back: 'Cheap (yasui)' },
  { id: 'v-24', deckId: 'n5-vocab', front: '新しい', back: 'New (atarashii)' },
  { id: 'v-25', deckId: 'n5-vocab', front: '古い', back: 'Old (furui)' },
  { id: 'v-26', deckId: 'n5-vocab', front: '良い', back: 'Good (ii/yoi)' },
  { id: 'v-27', deckId: 'n5-vocab', front: '悪い', back: 'Bad (warui)' },
  { id: 'v-28', deckId: 'n5-vocab', front: '今日', back: 'Today (kyou)' },
  { id: 'v-29', deckId: 'n5-vocab', front: '明日', back: 'Tomorrow (ashita)' },
  { id: 'v-30', deckId: 'n5-vocab', front: '昨日', back: 'Yesterday (kinou)' },
  { id: 'v-31', deckId: 'n5-vocab', front: '時間', back: 'Time (jikan)' },
  { id: 'v-32', deckId: 'n5-vocab', front: '今', back: 'Now (ima)' },
  { id: 'v-33', deckId: 'n5-vocab', front: '月曜日', back: 'Monday (getsuyoubi)' },
  { id: 'v-34', deckId: 'n5-vocab', front: '火曜日', back: 'Tuesday (kayoubi)' },
  { id: 'v-35', deckId: 'n5-vocab', front: '水曜日', back: 'Wednesday (suiyoubi)' },
  { id: 'v-36', deckId: 'n5-vocab', front: '木曜日', back: 'Thursday (mokuyoubi)' },
  { id: 'v-37', deckId: 'n5-vocab', front: '金曜日', back: 'Friday (kinyoubi)' },
  { id: 'v-38', deckId: 'n5-vocab', front: '土曜日', back: 'Saturday (doyoubi)' },
  { id: 'v-39', deckId: 'n5-vocab', front: '日曜日', back: 'Sunday (nichiyoubi)' },
  { id: 'v-40', deckId: 'n5-vocab', front: '一', back: 'One (ichi)' },
  { id: 'v-41', deckId: 'n5-vocab', front: '二', back: 'Two (ni)' },
  { id: 'v-42', deckId: 'n5-vocab', front: '三', back: 'Three (san)' },
  { id: 'v-43', deckId: 'n5-vocab', front: '四', back: 'Four (yon/shi)' },
  { id: 'v-44', deckId: 'n5-vocab', front: '五', back: 'Five (go)' },
  { id: 'v-45', deckId: 'n5-vocab', front: '六', back: 'Six (roku)' },
  { id: 'v-46', deckId: 'n5-vocab', front: '七', back: 'Seven (nana/shichi)' },
  { id: 'v-47', deckId: 'n5-vocab', front: '八', back: 'Eight (hachi)' },
  { id: 'v-48', deckId: 'n5-vocab', front: '九', back: 'Nine (kyuu/ku)' },
  { id: 'v-49', deckId: 'n5-vocab', front: '十', back: 'Ten (juu)' },
  { id: 'v-50', deckId: 'n5-vocab', front: '百', back: 'Hundred (hyaku)' },
  { id: 'v-51', deckId: 'n5-vocab', front: '千', back: 'Thousand (sen)' },
  { id: 'v-52', deckId: 'n5-vocab', front: '万', back: 'Ten thousand (man)' },
  { id: 'v-53', deckId: 'n5-vocab', front: '円', back: 'Yen (en)' },
  { id: 'v-54', deckId: 'n5-vocab', front: '人', back: 'Person (hito)' },
  { id: 'v-55', deckId: 'n5-vocab', front: '男', back: 'Man (otoko)' },
  { id: 'v-56', deckId: 'n5-vocab', front: '女', back: 'Woman (onna)' },
  { id: 'v-57', deckId: 'n5-vocab', front: '子', back: 'Child (ko)' },
  { id: 'v-58', deckId: 'n5-vocab', front: '家', back: 'House, home (ie, uchi)' },
  { id: 'v-59', deckId: 'n5-vocab', front: '車', back: 'Car (kuruma)' },
  { id: 'v-60', deckId: 'n5-vocab', front: '電気', back: 'Electricity, light (denki)' },
  { id: 'v-61', deckId: 'n5-vocab', front: '天気', back: 'Weather (tenki)' },
  { id: 'v-62', deckId: 'n5-vocab', front: '雨', back: 'Rain (ame)' },
  { id: 'v-63', deckId: 'n5-vocab', front: '雪', back: 'Snow (yuki)' },
  { id: 'v-64', deckId: 'n5-vocab', front: '電話', back: 'Telephone (denwa)' },
  { id: 'v-65', deckId: 'n5-vocab', front: '買う', back: 'To buy (kau)' },
  { id: 'v-66', deckId: 'n5-vocab', front: '売る', back: 'To sell (uru)' },
  { id: 'v-67', deckId: 'n5-vocab', front: '待つ', back: 'To wait (matsu)' },
  { id: 'v-68', deckId: 'n5-vocab', front: '持つ', back: 'To hold (motsu)' },
  { id: 'v-69', deckId: 'n5-vocab', front: '書く', back: 'To write (kaku)' },
  { id: 'v-70', deckId: 'n5-vocab', front: '読む', back: 'To read (yomu)' },
  { id: 'v-71', deckId: 'n5-vocab', front: '起きる', back: 'To get up (okiru)' },
  { id: 'v-72', deckId: 'n5-vocab', front: '寝る', back: 'To sleep (neru)' },
  { id: 'v-73', deckId: 'n5-vocab', front: '勉強する', back: 'To study (benkyou suru)' },
  { id: 'v-74', deckId: 'n5-vocab', front: '仕事する', back: 'To work (shigoto suru)' },
  { id: 'v-75', deckId: 'n5-vocab', front: 'はい', back: 'Yes (hai)' },
  { id: 'v-76', deckId: 'n5-vocab', front: 'いいえ', back: 'No (iie)' },
  { id: 'v-77', deckId: 'n5-vocab', front: 'これ', back: 'This (kore)' },
  { id: 'v-78', deckId: 'n5-vocab', front: 'それ', back: 'That (sore)' },
  { id: 'v-79', deckId: 'n5-vocab', front: 'あれ', back: 'That over there (are)' },
  { id: 'v-80', deckId: 'n5-vocab', front: 'どれ', back: 'Which one (dore)' },
  { id: 'v-81', deckId: 'n5-vocab', front: 'ここ', back: 'Here (koko)' },
  { id: 'v-82', deckId: 'n5-vocab', front: 'そこ', back: 'There (soko)' },
  { id: 'v-83', deckId: 'n5-vocab', front: 'あそこ', back: 'Over there (asoko)' },
  { id: 'v-84', deckId: 'n5-vocab', front: 'どこ', back: 'Where (doko)' },
  { id: 'v-85', deckId: 'n5-vocab', front: '誰', back: 'Who (dare)' },
  { id: 'v-86', deckId: 'n5-vocab', front: '何', back: 'What (nani/nan)' },
  { id: 'v-87', deckId: 'n5-vocab', front: 'いつ', back: 'When (itsu)' },
  { id: 'v-88', deckId: 'n5-vocab', front: 'どうして', back: 'Why (doushite)' },
  { id: 'v-89', deckId: 'n5-vocab', front: '上手', back: 'Skillful, good at (jouzu)' },
  { id: 'v-90', deckId: 'n5-vocab', front: '下手', back: 'Unskillful, bad at (heta)' },
  { id: 'v-91', deckId: 'n5-vocab', front: '好き', back: 'To like (suki)' },
  { id: 'v-92', deckId: 'n5-vocab', front: '嫌い', back: 'To dislike (kirai)' },
  { id: 'v-93', deckId: 'n5-vocab', front: '食べ物', back: 'Food (tabemono)' },
  { id: 'v-94', deckId: 'n5-vocab', front: '飲み物', back: 'Drink (nomimono)' },
  { id: 'v-95', deckId: 'n5-vocab', front: '映画', back: 'Movie (eiga)' },
  { id: 'v-96', deckId: 'n5-vocab', front: '音楽', back: 'Music (ongaku)' },
  { id: 'v-97', deckId: 'n5-vocab', front: 'スポーツ', back: 'Sports (supo-tsu)' },
  { id: 'v-98', deckId: 'n5-vocab', front: '店', back: 'Store, shop (mise)' },
  { id: 'v-99', deckId: 'n5-vocab', front: '駅', back: 'Station (eki)' },
  { id: 'v-100', deckId: 'n5-vocab', front: '飛行機', back: 'Airplane (hikouki)' },
  
  // N4 Vocab (150 cards, showing a few)
  { id: 'v4-1', deckId: 'n4-vocab', front: '意見', back: 'Opinion (iken)' },
  { id: 'v4-2', deckId: 'n4-vocab', front: '経験', back: 'Experience (keiken)' },
  { id: 'v4-3', deckId: 'n4-vocab', front: '文化', back: 'Culture (bunka)' },
  { id: 'v4-4', deckId: 'n4-vocab', front: '将来', back: 'Future (shourai)' },
  { id: 'v4-5', deckId: 'n4-vocab', front: '続ける', back: 'To continue (tsuzukeru)' },

  // N3 Vocab
  { id: 'v3-1', deckId: 'n3-vocab', front: '解決', back: 'Solution, resolution (kaiketsu)' },
  { id: 'v3-2', deckId: 'n3-vocab', front: '影響', back: 'Influence, effect (eikyou)' },
  { id: 'v3-3', deckId: 'n3-vocab', front: '努力', back: 'Effort, endeavor (doryoku)' },
  { id: 'v3-4', deckId: 'n3-vocab', front: '生産', back: 'Production (seisan)' },
  { id: 'v3-5', deckId: 'n3-vocab', front: '開発', back: 'Development (kaihatsu)' },
  
  // N2 Vocab
  { id: 'v2-1', deckId: 'n2-vocab', front: '議論', back: 'Argument, discussion (giron)' },
  { id: 'v2-2', deckId: 'n2-vocab', front: '貢献', back: 'Contribution (kouken)' },
  { id: 'v2-3', deckId: 'n2-vocab', front: '哲学', back: 'Philosophy (tetsugaku)' },
  { id: 'v2-4', deckId: 'n2-vocab', front: '組織', back: 'Organization (soshiki)' },
  { id: 'v2-5', deckId: 'n2-vocab', front: '法律', back: 'Law (houritsu)' },

  // N1 Vocab
  { id: 'v1-1', deckId: 'n1-vocab', front: '普遍的', back: 'Universal (fuhenteki)' },
  { id: 'v1-2', deckId: 'n1-vocab', front: '抽象的', back: 'Abstract (chuushouteki)' },
  { id: 'v1-3', deckId: 'n1-vocab', front: '矛盾', back: 'Contradiction (mujun)' },
  { id: 'v1-4', deckId: 'n1-vocab', front: '規範', back: 'Norm, standard (kihan)' },
  { id: 'v1-5', deckId: 'n1-vocab', front: '概念', back: 'Concept, idea (gainen)' },
];

export const grammarPoints: GrammarPoint[] = [
  // N5
  {
    id: 'g-1',
    level: 'N5',
    title: 'AはBです (A wa B desu)',
    explanation: 'This is the most basic sentence structure in Japanese. It is used to state that "A is B". 「は」 (wa) is a topic particle, and 「です」 (desu) is a copula, similar to "is" or "am" or "are" in English.',
    examples: [
      { question: 'わたし___がくせいです。', answer: 'は', options: ['が', 'を', 'も'], sentence: 'わたしはがくせいです。', translation: 'I am a student.' },
      { question: 'これ___ほんです。', answer: 'は', options: ['に', 'で', 'と'], sentence: 'これはほんです。', translation: 'This is a book.' },
    ],
  },
  {
    id: 'g-2',
    level: 'N5',
    title: 'Verb Conjugation (ます-form)',
    explanation: 'The ます (masu) form is the polite, non-past form of a verb. It is commonly used in daily conversation. To form it, you typically change the final "u" sound of the dictionary form verb to an "i" and add ます. For example, "kau" (to buy) becomes "kaimasu".',
    examples: [
      { question: 'わたしはほんを___。', answer: 'かいます', options: ['かう', 'かって', 'かった'], sentence: 'わたしはほんをかいます。', translation: 'I buy a book.' },
      { question: 'かれはすしを___。', answer: 'たべます', options: ['たべる', 'たべて', 'たべた'], sentence: 'かれはすしをたべます。', translation: 'He eats sushi.' },
    ],
  },
  {
    id: 'g-3',
    level: 'N5',
    title: 'Possessive Particle 「の」 (no)',
    explanation: 'The particle 「の」 (no) is used to show possession, similar to "apostrophe s" in English. It links two nouns, where the first noun possesses or describes the second noun.',
    examples: [
      { question: 'これはわたし___ペンです。', answer: 'の', options: ['が', 'を', 'は'], sentence: 'これはわたしのペンです。', translation: 'This is my pen.' },
      { question: 'さくらさん___かばんは大きいです。', answer: 'の', options: ['と', 'も', 'や'], sentence: 'さくらさんのかばんは大きいです。', translation: "Sakura's bag is big." },
    ],
  },
  {
    id: 'g-4',
    level: 'N5',
    title: 'Purpose of movement (~に 行きます)',
    explanation: 'To express the purpose of going somewhere, you can use the structure: "Place に Verb Stem + に 行きます/来ます/帰ります". The verb stem is the ます-form of a verb without the ます.',
    examples: [
      { question: 'わたしはえいがを___にいきます。', answer: 'み', options: ['みます', 'みる', 'み'], sentence: 'わたしはえいがをみにいきます。', translation: 'I am going to watch a movie.' },
      { question: 'レストランへごはんを___にいきます。', answer: 'たべ', options: ['たべる', 'たべます', 'たべ'], sentence: 'レストランへごはんをたべにいきます。', translation: 'I am going to the restaurant to eat a meal.' },
    ],
  },
  {
    id: 'g-5',
    level: 'N5',
    title: 'Making invitations (~ませんか)',
    explanation: 'To invite someone to do something, you can use the negative question form of a verb: 「~ませんか」 (masen ka?). This is a polite way to say "Won\'t you...?" or "How about...?".',
    examples: [
      { question: 'いっしょにえいがをみ___か。', answer: 'ませんか', options: ['ます', 'ません', 'ませんか'], sentence: 'いっしょにえいがをみませんか。', translation: 'Won\'t you watch a movie with me?' },
      { question: 'こーひーをのみ___か。', answer: 'ませんか', options: ['ます', 'ました', 'ませんか'], sentence: 'こーひーをのみませんか。', translation: 'How about drinking some coffee?' },
    ],
  },
   {
    id: 'g-6',
    level: 'N5',
    title: 'Direct Object Particle 「を」 (o)',
    explanation: 'The particle 「を」 (o/wo) marks the direct object of a verb. It is placed after a noun to indicate that the noun is the thing being directly acted upon by the verb.',
    examples: [
      { question: 'わたしはほん___よみます。', answer: 'を', options: ['が', 'は', 'に'], sentence: 'わたしはほんをよみます。', translation: 'I read a book.' },
      { question: 'かれはみず___のみます。', answer: 'を', options: ['で', 'と', 'へ'], sentence: 'かれはみずをのみます。', translation: 'He drinks water.' },
    ],
  },
  {
    id: 'g-12',
    level: 'N5',
    title: 'Location of Action Particle 「で」 (de)',
    explanation: 'The particle 「で」 (de) is used to indicate the location where an action takes place. It answers the question "where did the action happen?".',
    examples: [
      { question: 'わたしはとしょかん___べんきょうします。', answer: 'で', options: ['に', 'へ', 'で'], sentence: 'わたしはとしょかんでべんきょうします。', translation: 'I study at the library.' },
      { question: 'レストラン___ひるごはんをたべました。', answer: 'で', options: ['を', 'に', 'で'], sentence: 'レストランでひるごはんをたべました。', translation: 'I ate lunch at the restaurant.' },
    ],
  },
  {
    id: 'g-13',
    level: 'N5',
    title: 'Verbs of Existence 「います」 & 「あります」',
    explanation: '「います」 (imasu) is used for the existence of animate things (people, animals), while 「あります」 (arimasu) is for inanimate things (objects, plants). Both mean "to be" or "to exist". The location particle is 「に」.',
    examples: [
      { question: 'へやにねこが___。', answer: 'います', options: ['あります', 'います', 'です'], sentence: 'へやにねこがいます。', translation: 'There is a cat in the room.' },
      { question: 'つくえのうえにほんが___。', answer: 'あります', options: ['あります', 'います', 'です'], sentence: 'つくえのうえにほんがあります。', translation: 'There is a book on the desk.' },
    ],
  },
  {
    id: 'g-14',
    level: 'N5',
    title: 'Past Tense (~ました / ~でした)',
    explanation: 'To talk about the past, verbs in ます-form change to ました (mashita). For nouns and na-adjectives, です (desu) changes to でした (deshita). For i-adjectives, the final い (i) changes to かったです (katta desu).',
    examples: [
      { question: 'きのう、えいがを___。', answer: 'みました', options: ['みます', 'みました', 'みて'], sentence: 'きのう、えいがをみました。', translation: 'I watched a movie yesterday.' },
      { question: 'きのうはあめ___。', answer: 'でした', options: ['です', 'でした', 'で'], sentence: 'きのうはあめでした。', translation: 'It was rainy yesterday.' },
    ],
  },
  {
    id: 'g-15',
    level: 'N5',
    title: 'Adjective Usage (~い / ~な)',
    explanation: 'There are two types of adjectives. い-adjectives end with い (e.g., おおきい) and come directly before a noun. な-adjectives require a な (na) particle when they come before a noun (e.g., きれいな).',
    examples: [
      { question: 'これは___ほんです。', answer: 'あたらしい', options: ['あたらしいな', 'あたらしいの', 'あたらしい'], sentence: 'これはあたらしいほんです。', translation: 'This is a new book.' },
      { question: 'しずか___まちです。', answer: 'な', options: ['の', 'な', 'い'], sentence: 'しずかなまちです。', translation: 'It is a quiet town.' },
    ],
  },
  // N4
  {
    id: 'g-7',
    level: 'N4',
    title: 'Potential Form (~ことができます / ~れる/られる)',
    explanation: 'This form expresses ability ("can do something"). One way is to use "Dictionary Form Verb + ことができます". Another is to conjugate the verb itself. For る-verbs, change る to られる. For う-verbs, change the final "u" vowel to "e" and add る.',
    examples: [
      { question: 'わたしはかんじをよむ___ができます。', answer: 'こと', options: ['の', 'もの', 'とき'], sentence: 'わたしはかんじをよむことができます。', translation: 'I can read Kanji.' },
      { question: 'かれはすしが___。', answer: 'たべられます', options: ['たべます', 'たべたい', 'たべる'], sentence: 'かれはすしがたべられます。', translation: 'He can eat sushi.' },
    ],
  },
  {
    id: 'g-8',
    level: 'N4',
    title: 'Conditional Form (~たら)',
    explanation: 'The 「たら」 (tara) form is a common way to express "if" or "when". It\'s formed by taking the past tense of a verb or adjective and adding 「ら」 (ra). It can be used for a wide range of conditional situations.',
    examples: [
      { question: 'にほんに___、さくらをみたいです。', answer: 'いったら', options: ['いくと', 'いけば', 'いくなら'], sentence: 'にほんにいったら、さくらをみたいです。', translation: 'If/When I go to Japan, I want to see the cherry blossoms.' },
      { question: 'やす___、かいます。', answer: 'かったら', options: ['ければ', 'いと', 'く'], sentence: 'やすかったら、かいます。', translation: "If it's cheap, I'll buy it." },
    ],
  },
  {
    id: 'g-9',
    level: 'N4',
    title: 'Hearsay (~そうです)',
    explanation: 'To report something you heard, you can add 「そうです」 (sou desu) to the dictionary form of verbs and i-adjectives, or to the stem of na-adjectives and nouns. It translates to "I heard that..." or "It seems that...".',
    examples: [
      { question: 'てんきよほうによると、あしたはあめがふる___です。', answer: 'そう', options: ['よう', 'みたい', 'そう'], sentence: 'てんきよほうによると、あしたはあめがふるそうです。', translation: 'According to the weather forecast, I heard it will rain tomorrow.' },
      { question: 'あのレストランはおいしい___です。', answer: 'そう', options: ['よう', 'そう', 'らしい'], sentence: 'あのレストランはおいしいそうです。', translation: 'I heard that restaurant is delicious.' },
    ],
  },
  {
    id: 'g-10',
    level: 'N4',
    title: 'Easy/Hard to do (~やすい / ~にくい)',
    explanation: 'Attach 「やすい」 (yasui) or 「にくい」 (nikui) to the verb stem (ます-form without ます) to express that something is "easy to do" or "hard to do", respectively.',
    examples: [
      { question: 'このかんじは___やすいです。', answer: 'おぼえ', options: ['おぼえる', 'おぼえて', 'おぼえ'], sentence: 'このかんじはおぼえやすいです。', translation: 'This kanji is easy to remember.' },
      { question: 'このくつは___にくいです。', answer: 'あるき', options: ['あるく', 'あるいて', 'あるき'], sentence: 'このくつはあるきにくいです。', translation: 'These shoes are hard to walk in.' },
    ],
  },
  {
    id: 'g-11',
    level: 'N4',
    title: 'Volitional Form (~よう / ~おう)',
    explanation: 'The volitional form expresses intention ("let\'s do..."). For る-verbs, change る to よう. For う-verbs, change the final "u" vowel to "o" and add う.',
    examples: [
      { question: 'えいがを___。', answer: 'みよう', options: ['みます', 'みよう', 'みたい'], sentence: 'えいがをみよう。', translation: 'Let\'s watch a movie.' },
      { question: 'いっしょに___。', answer: 'いこう', options: ['いきます', 'いく', 'いこう'], sentence: 'いっしょにいこう。', translation: 'Let\'s go together.' },
    ],
  },
  // N3
  {
    id: 'g-16',
    level: 'N3',
    title: 'Passive Form (~れる/られる)',
    explanation: 'The passive voice is used when the subject of the sentence is being acted upon. For る-verbs, change る to られる. For う-verbs, change the final "u" vowel to "a" and add れる.',
    examples: [
        { question: 'この本は多くの人に___います。', answer: '読まれて', options: ['読んで', '読ませて', '読まれて'], sentence: 'この本は多くの人に読まれています。', translation: 'This book is read by many people.' },
        { question: '私は先生に___。', answer: '褒められました', options: ['褒めました', '褒めさせました', '褒められました'], sentence: '私は先生に褒められました。', translation: 'I was praised by the teacher.' },
    ],
  },
  {
      id: 'g-17',
      level: 'N3',
      title: 'Causative Form (~せる/させる)',
      explanation: 'The causative form expresses that someone makes or lets someone do something. For る-verbs, change る to させる. For う-verbs, change the final "u" vowel to "a" and add せる.',
      examples: [
          { question: '母は私に部屋を___。', answer: '掃除させました', options: ['掃除しました', '掃除させました', '掃除されました'], sentence: '母は私に部屋を掃除させました。', translation: 'My mother made me clean the room.' },
          { question: '先生は生徒に本を___。', answer: '読ませます', options: ['読みます', '読ませます', '読まれます'], sentence: '先生は生徒に本を読ませます。', translation: 'The teacher makes the students read books.' },
      ],
  },
  {
    id: 'g-18',
    level: 'N3',
    title: '~うちに (While/before)',
    explanation: 'Expresses that something should be done while a certain condition is true, or before a change occurs. It often carries a sense of opportunity or urgency.',
    examples: [
      { question: 'あたたかい___、どうぞめしあがってください。', answer: 'うちに', options: ['あいだに', 'うちに', 'ときに'], sentence: 'あたたかいうちに、どうぞめしあがってください。', translation: 'Please eat while it\'s warm.' },
      { question: 'わかいうちに、たくさん___したほうがいい。', answer: 'べんきょう', options: ['あそんで', 'べんきょう', 'ねて'], sentence: 'わかいうちに、たくさんべんきょうしたほうがいい。', translation: 'You should study a lot while you are young.' },
    ],
  },
  {
    id: 'g-19',
    level: 'N3',
    title: '~おかげで / ~せいで (Thanks to / due to)',
    explanation: '「おかげで」 is used for positive outcomes, meaning "thanks to...". 「せいで」 is used for negative outcomes, meaning "due to..." or "because of...".',
    examples: [
      { question: '先生の___、しけんにごうかくできました。', answer: 'おかげで', options: ['おかげで', 'せいで', 'ために'], sentence: '先生のおかげで、しけんにごうかくできました。', translation: 'Thanks to my teacher, I was able to pass the exam.' },
      { question: 'バスがおくれた___、かいぎにちこくした。', answer: 'せいで', options: ['おかげで', 'せいで', 'から'], sentence: 'バスがおくれたせいで、かいぎにちこくした。', translation: 'I was late for the meeting because the bus was late.' },
    ],
  },
  {
    id: 'g-20',
    level: 'N3',
    title: '~はずだ (Should be/expected to be)',
    explanation: 'Expresses a high degree of certainty based on evidence or logic. It means "it is expected that...", "it should be the case that...", or "I\'m sure that...".',
    examples: [
      { question: 'かれはきのうここに来た___です。', answer: 'はず', options: ['そう', 'よう', 'はず'], sentence: 'かれはきのうここに来たはずです。', translation: 'He should have come here yesterday.' },
      { question: 'くすりをのんだから、ねつはさがる___だ。', answer: 'はず', options: ['はず', 'わけ', 'こと'], sentence: 'くすりをのんだから、ねつはさがるはずだ。', translation: 'Since I took the medicine, my fever is expected to go down.' },
    ],
  },
  // N2
  {
    id: 'g-21',
    level: 'N2',
    title: '~わけだ (No wonder)',
    explanation: 'Used to indicate a natural conclusion based on the preceding context. It translates to "it makes sense that...", "no wonder...", or "that\'s why...".',
    examples: [
      { question: '彼は日本に10年住んでいる。日本語が上手な___。', answer: 'わけだ', options: ['はずだ', 'わけだ', 'つもりだ'], sentence: '彼は日本に10年住んでいる。日本語が上手なわけだ。', translation: 'He has lived in Japan for 10 years. No wonder his Japanese is so good.' },
      { question: '夜中にたくさん食べたから、お腹が痛い___。', answer: 'わけだ', options: ['わけだ', 'ことだ', 'ものだ'], sentence: '夜中にたくさん食べたから、お腹が痛いわけだ。', translation: "I ate a lot late at night, that's why my stomach hurts." },
    ],
  },
  {
    id: 'g-22',
    level: 'N2',
    title: '~得る/うる (Can/possible)',
    explanation: 'A formal way to say something is possible. It attaches to the verb stem (ます-form without ます). The negative form is ~得ない (enai).',
    examples: [
      { question: 'この状況では、事故が起こり___。', answer: '得る', options: ['得る', '過ぎる', 'がちだ'], sentence: 'この状況では、事故が起こり得る。', translation: 'In this situation, an accident could happen.' },
      { question: 'それはあり___話だ。', answer: '得ない', options: ['得ない', 'わけがない', 'はずがない'], sentence: 'それはあり得ない話だ。', translation: 'That is an impossible story.' },
    ],
  },
  {
    id: 'g-23',
    level: 'N2',
    title: '~うえに (On top of that)',
    explanation: 'Used to add another fact or reason, usually in the same positive or negative direction. It means "in addition to...", "on top of that...".',
    examples: [
      { question: 'このレストランは、値段が高い___、サービスも悪い。', answer: 'うえに', options: ['ばかりか', 'うえに', 'どころか'], sentence: 'このレストランは、値段が高いうえに、サービスも悪い。', translation: 'This restaurant is expensive, and on top of that, the service is bad.' },
      { question: '彼女は美しい___、頭もいい。', answer: 'うえに', options: ['うえに', 'かわりに', 'いっぽうで'], sentence: '彼女は美しいうえに、頭もいい。', translation: 'She is beautiful, and moreover, she is smart.' },
    ],
  },
  {
    id: 'g-24',
    level: 'N2',
    title: '~にこたえて (In response to)',
    explanation: 'Indicates that an action is done in response to expectations, requests, or hopes. It is a formal expression.',
    examples: [
      { question: 'ファンの期待___、すばらしいパフォーマンスを見せた。', answer: 'にこたえて', options: ['について', 'にたいして', 'にこたえて'], sentence: 'ファンの期待にこたえて、すばらしいパフォーマンスを見せた。', translation: 'In response to the fans\' expectations, they gave a wonderful performance.' },
      { question: '地域住民の要望___、新しい公園が建設された。', answer: 'にこたえて', options: ['にしたがって', 'にこたえて', 'にもとづいて'], sentence: '地域住民の要望にこたえて、新しい公園が建設された。', translation: 'A new park was built in response to the residents\' requests.' },
    ],
  },
  {
    id: 'g-25',
    level: 'N2',
    title: '~反面 (On the other hand)',
    explanation: 'Used to present two opposing aspects of the same thing. It is similar to "on the other hand" or "while".',
    examples: [
      { question: '都会の生活は便利な___、ストレスも多い。', answer: '反面', options: ['反面', 'いっぽうで', 'かわりに'], sentence: '都会の生活は便利な反面、ストレスも多い。', translation: 'City life is convenient, but on the other hand, it is also very stressful.' },
      { question: 'この薬はよく効く___、副作用も強い。', answer: '反面', options: ['反面', 'うえに', 'ばかりに'], sentence: 'この薬はよく効く反面、副作用も強い。', translation: 'This medicine is effective, but on the other hand, it has strong side effects.' },
    ],
  },
  // N1
  {
    id: 'g-26',
    level: 'N1',
    title: '~かのようだ (As if)',
    explanation: 'Expresses that something appears to be a certain way, even though it isn\'t true. It creates a simile. It is often used with まるで (marude).',
    examples: [
      { question: '彼はまるで全てを知っている___話す。', answer: 'かのように', options: ['かのように', 'ばかりに', 'だけあって'], sentence: '彼はまるで全てを知っているかのように話す。', translation: 'He talks as if he knows everything.' },
      { question: '彼女は、何もなかった___振る舞った。', answer: 'かのように', options: ['かのように', 'ものなら', 'とあれば'], sentence: '彼女は、何もなかったかのように振る舞った。', translation: 'She behaved as if nothing had happened.' },
    ],
  },
  {
    id: 'g-27',
    level: 'N1',
    title: '~ずにはいられない (Can\'t help but do)',
    explanation: 'Expresses an uncontrollable urge or feeling to do something. It\'s formed with the verb negative stem (ない-form without ない) + ずにはいられない.',
    examples: [
      { question: 'その光景を見て、涙を流さ___。', answer: 'ずにはいられなかった', options: ['ずにはいられなかった', 'ないではなかった', 'ないわけではなかった'], sentence: 'その光景を見て、涙を流さずにはいられなかった。', translation: 'Seeing that sight, I couldn\'t help but cry.' },
      { question: '彼の冗談には笑わ___。', answer: 'ずにはいられない', options: ['ないではいられない', 'ずにはいられない', 'ないこともない'], sentence: '彼の冗談には笑わずにはいられない。', translation: 'I can\'t help but laugh at his jokes.' },
    ],
  },
  {
    id: 'g-28',
    level: 'N1',
    title: '~極まる / ~極まりない (Extremely)',
    explanation: 'An emphatic way to say "extremely" or "the height of...". It attaches to the stem of na-adjectives or nouns. 「極まる」 (kiwamaru) is a bit more literary than 「極まりない」 (kiwamarinai).',
    examples: [
      { question: '彼の態度は失礼___。', answer: '極まる', options: ['極まる', 'きりだ', 'しかない'], sentence: '彼の態度は失礼極まる。', translation: 'His attitude is extremely rude.' },
      { question: '危険___ことだ。', answer: '極まりない', options: ['極まりない', 'にすぎない', 'にほかならない'], sentence: '危険極まりないことだ。', translation: 'It is an extremely dangerous thing.' },
    ],
  },
  {
    id: 'g-29',
    level: 'N1',
    title: '~とあれば (If it\'s the case that)',
    explanation: 'A conditional expression used for special or exceptional situations. It implies a strong resolve or willingness to act if the condition is met. "If it\'s for...", "If it means...".',
    examples: [
      { question: '子供のため___、どんなことでもします。', answer: 'とあれば', options: ['とあれば', 'としたら', 'とすれば'], sentence: '子供のためとあれば、どんなことでもします。', translation: 'If it\'s for my children, I will do anything.' },
      { question: '優勝がかかっている___、全力で戦うしかない。', answer: 'とあれば', options: ['とあれば', 'ともなると', 'にあって'], sentence: '優勝がかかっているとあれば、全力で戦うしかない。', translation: 'If the championship is on the line, we have no choice but to fight with all our might.' },
    ],
  },
  {
    id: 'g-30',
    level: 'N1',
    title: '~を皮切りに (Starting with)',
    explanation: 'Indicates the starting point of a series of similar events or actions that then expand or continue. It implies a chain reaction.',
    examples: [
      { question: 'この展覧会は東京___、全国各地で開催される。', answer: 'を皮切りに', options: ['をはじめ', 'を皮切りに', 'からして'], sentence: 'この展覧-覧会は東京を皮切りに、全国各地で開催される。', translation: 'Starting with Tokyo, this exhibition will be held in various places nationwide.' },
      { question: '彼の発言___、議論が巻き起こった。', answer: 'を皮切りに', options: ['をきっかけに', 'を皮切りに', 'をめぐって'], sentence: '彼の発言を皮切りに、議論が巻き起こった。', translation: 'Starting with his remark, a debate broke out.' },
    ],
  },
];

export const quizzes: QuizMeta[] = [
    {
        id: 'grammar-n5',
        type: 'grammar',
        title: 'Grammar Quiz',
        description: 'Test your knowledge of N5 grammar points.',
        level: 'N5',
    },
    {
        id: 'grammar-n4',
        type: 'grammar',
        title: 'Grammar Quiz',
        description: 'Test your knowledge of N4 grammar points.',
        level: 'N4',
    },
     {
        id: 'grammar-n3',
        type: 'grammar',
        title: 'Grammar Quiz',
        description: 'Test your knowledge of N3 grammar points.',
        level: 'N3',
    },
     {
        id: 'grammar-n2',
        type: 'grammar',
        title: 'Grammar Quiz',
        description: 'Test your knowledge of N2 grammar points.',
        level: 'N2',
    },
     {
        id: 'grammar-n1',
        type: 'grammar',
        title: 'Grammar Quiz',
        description: 'Test your knowledge of N1 grammar points.',
        level: 'N1',
    },
    {
        id: 'vocabulary-n5',
        type: 'vocabulary',
        title: 'Vocabulary Quiz',
        description: 'A quiz on essential N5 flashcards.',
        level: 'N5',
    },
    {
        id: 'vocabulary-n4',
        type: 'vocabulary',
        title: 'Vocabulary Quiz',
        description: 'A quiz on intermediate N4 flashcards.',
        level: 'N4',
    },
    {
        id: 'vocabulary-n3',
        type: 'vocabulary',
        title: 'Vocabulary Quiz',
        description: 'A quiz on upper-intermediate N3 flashcards.',
        level: 'N3',
    },
    {
        id: 'vocabulary-n2',
        type: 'vocabulary',
        title: 'Vocabulary Quiz',
        description: 'A quiz on pre-advanced N2 flashcards.',
        level: 'N2',
    },
    {
        id: 'vocabulary-n1',
        type: 'vocabulary',
        title: 'Vocabulary Quiz',
        description: 'A quiz on advanced N1 flashcards.',
        level: 'N1',
    },
    {
        id: 'listening-n5',
        type: 'listening',
        title: 'Listening Comprehension',
        description: 'Listen to basic sentences and write what you hear.',
        level: 'N5',
    },
    {
        id: 'listening-n4',
        type: 'listening',
        title: 'Listening Comprehension',
        description: 'Listen to intermediate sentences and write what you hear.',
        level: 'N4',
    },
    {
        id: 'listening-n3',
        type: 'listening',
        title: 'Listening Comprehension',
        description: 'Listen to upper-intermediate sentences.',
        level: 'N3',
    },
    {
        id: 'listening-n2',
        type: 'listening',
        title: 'Listening Comprehension',
        description: 'Listen to pre-advanced sentences.',
        level: 'N2',
    },
    {
        id: 'listening-n1',
        type: 'listening',
        title: 'Listening Comprehension',
        description: 'Listen to advanced and natural-speed sentences.',
        level: 'N1',
    },
    {
        id: 'creative-practice',
        type: 'creative-practice',
        title: 'Creative Practice',
        description: 'Test your skills by creating sentences that fit certain conditions, validated by AI.',
    },
    {
        id: 'review-quiz',
        type: 'review',
        title: 'Review Quiz',
        description: 'Practice all the questions you have answered incorrectly across all quizzes.'
    }
];

export const listeningSentences: ListeningQuizQuestion[] = [
    //N5
    { id: 'l-1', kana: 'こんにちは', romaji: 'Konnichiwa', level: 'N5' },
    { id: 'l-2', kana: 'ありがとうございます', romaji: 'Arigatou gozaimasu', level: 'N5' },
    { id: 'l-3', kana: 'すみません', romaji: 'Sumimasen', level: 'N5' },
    { id: 'l-4', kana: 'はい、そうです', romaji: 'Hai, sou desu', level: 'N5' },
    { id: 'l-5', kana: 'これはいくらですか', romaji: 'Kore wa ikura desu ka', level: 'N5' },
    // N4
    { id: 'l-11', kana: 'レストランは三階にあります', romaji: 'Resutoran wa sankai ni arimasu', level: 'N4' },
    { id: 'l-12', kana: 'このバスはとうきょうえきにいきますか', romaji: 'Kono basu wa Tokyo-eki ni ikimasu ka', level: 'N4' },
    { id: 'l-13', kana: 'もっとゆっくりはなしてください', romaji: 'Motto yukkuri hanashite kudasai', level: 'N4' },
    // N3
    { id: 'l-21', kana: 'その問題を解決するために、私たちは協力すべきです。', romaji: 'Sono mondai o kaiketsu suru tame ni, watashitachi wa kyōryoku subeki desu.', level: 'N3' },
    { id: 'l-22', kana: '彼のスピーチは聴衆に大きな影響を与えました。', romaji: 'Kare no supīchi wa chōshū ni ōkina eikyō o ataemashita.', level: 'N3' },
    // N2
    { id: 'l-31', kana: '環境問題に関する議論が活発に行われています。', romaji: 'Kankyō mondai ni kansuru giron ga kappatsu ni okonawarete imasu.', level: 'N2' },
    { id: 'l-32', kana: '彼は地域社会の発展に大きく貢献した。', romaji: 'Kare wa chiiki shakai no hatten ni ōkiku kōken shita.', level: 'N2' },
    // N1
    { id: 'l-41', kana: '自由という概念は普遍的価値を持つと考えられている。', romaji: 'Jiyū to iu gainen wa fuhenteki kachi o motsu to kangaerarete iru.', level: 'N1' },
    { id: 'l-42', kana: '彼の理論は抽象的すぎて、具体的な応用が難しい。', romaji: 'Kare no riron wa chūshōtekisugite, gutaitekina ōyō ga muzukashii.', level: 'N1' },
];

export const creativeChallenges: CreativeChallenge[] = [
    { id: 'cc-1', conditions: ['Greetings', 'Politeness'] },
    { id: 'cc-2', conditions: ['Ask for price', 'A drink'] },
    { id: 'cc-3', conditions: ['Express gratitude', 'Receiving a gift'] },
    { id: 'cc-4', conditions: ['Introduce yourself', 'Mention your nationality'] },
    { id: 'cc-5', conditions: ['Ask for directions', 'Train station'] },
    { id: 'cc-6', conditions: ['Make a reservation', 'For two people'] },
    { id: 'cc-7', conditions: ['State a preference', 'Food', 'Dislike'] },
    { id: 'cc-8', conditions: ['Describe an object', 'Color: red', 'Size: small'] },
    { id: 'cc-9', conditions: ['Talk about a hobby', 'Reading books'] },
    { id: 'cc-10', conditions: ['Apologize', 'For being late'] },
    { id: 'cc-11', conditions: ['Ask for permission', 'Take a photo'] },
    { id: 'cc-12', conditions: ['Describe ability', 'Speak Japanese a little'] },
    { id: 'cc-13', conditions: ['Talk about weather', 'It is hot today'] },
    { id: 'cc-14', conditions: ['Express desire', 'Want to go to Japan'] },
    { id: 'cc-15', conditions: ['Describe past action', 'Ate sushi yesterday'] },
    { id: 'cc-16', conditions: ['Give a compliment', 'To a friend', 'On their new bag'] },
    { id: 'cc-17', conditions: ['Ask about experience', 'Have you ever been to Kyoto?'] },
    { id: 'cc-18', conditions: ['Make a suggestion', 'Let\'s watch a movie'] },
    { id: 'cc-19', conditions: ['Refuse politely', 'An invitation'] },
    { id: 'cc-20', conditions: ['Talk about future plans', 'Study Japanese tomorrow'] },
];

    
