import type { Deck, Card, GrammarPoint, QuizMeta, ListeningQuizQuestion, CreativeChallenge } from './types';

export const basicDecks: Deck[] = [
  {
    id: 'hiragana',
    name: 'Hiragana Basics',
    description: 'Master the fundamental Japanese syllabary.',
    cardCount: 46,
    isCustom: false,
  },
  {
    id: 'katakana',
    name: 'Katakana Practice',
    description: 'Learn the script used for foreign words.',
    cardCount: 46,
    isCustom: false,
  },
  {
    id: 'n5-vocab',
    name: 'JLPT N5 Vocabulary',
    description: 'Essential words for beginner proficiency.',
    cardCount: 100,
    isCustom: false,
  },
   {
    id: 'n4-vocab',
    name: 'JLPT N4 Vocabulary',
    description: 'Intermediate words for expanding your vocabulary.',
    cardCount: 150,
    isCustom: false,
  },
];

export const cards: Card[] = [
  // Hiragana (46 cards)
  { id: 'h-1', deckId: 'hiragana', front: 'あ', back: 'a' },
  { id: 'h-2', deckId: 'hiragana', front: 'い', back: 'i' },
  { id: 'h-3', deckId: 'hiragana', front: 'う', back: 'u' },
  { id: 'h-4', deckId: 'hiragana', front: 'え', back: 'e' },
  { id: 'h-5', deckId: 'hiragana', front: 'お', back: 'o' },
  { id: 'h-6', deckId: 'hiragana', front: 'か', back: 'ka' },
  { id: 'h-7', deckId: 'hiragana', front: 'き', back: 'ki' },
  { id: 'h-8', deckId: 'hiragana', front: 'く', back: 'ku' },
  { id: 'h-9', deckId: 'hiragana', front: 'け', back: 'ke' },
  { id: 'h-10', deckId: 'hiragana', front: 'こ', back: 'ko' },
  { id: 'h-11', deckId: 'hiragana', front: 'さ', back: 'sa' },
  { id: 'h-12', deckId: 'hiragana', front: 'し', back: 'shi' },
  { id: 'h-13', deckId: 'hiragana', front: 'す', back: 'su' },
  { id: 'h-14', deckId: 'hiragana', front: 'せ', back: 'se' },
  { id: 'h-15', deckId: 'hiragana', front: 'そ', back: 'so' },
  { id: 'h-16', deckId: 'hiragana', front: 'た', back: 'ta' },
  { id: 'h-17', deckId: 'hiragana', front: 'ち', back: 'chi' },
  { id: 'h-18', deckId: 'hiragana', front: 'つ', back: 'tsu' },
  { id: 'h-19', deckId: 'hiragana', front: 'て', back: 'te' },
  { id: 'h-20', deckId: 'hiragana', front: 'と', back: 'to' },
  { id: 'h-21', deckId: 'hiragana', front: 'な', back: 'na' },
  { id: 'h-22', deckId: 'hiragana', front: 'に', back: 'ni' },
  { id: 'h-23', deckId: 'hiragana', front: 'ぬ', back: 'nu' },
  { id: 'h-24', deckId: 'hiragana', front: 'ね', back: 'ne' },
  { id: 'h-25', deckId: 'hiragana', front: 'の', back: 'no' },
  { id: 'h-26', deckId: 'hiragana', front: 'は', back: 'ha' },
  { id: 'h-27', deckId: 'hiragana', front: 'ひ', back: 'hi' },
  { id: 'h-28', deckId: 'hiragana', front: 'ふ', back: 'fu' },
  { id: 'h-29', deckId: 'hiragana', front: 'へ', back: 'he' },
  { id: 'h-30', deckId: 'hiragana', front: 'ほ', back: 'ho' },
  { id: 'h-31', deckId: 'hiragana', front: 'ま', back: 'ma' },
  { id: 'h-32', deckId: 'hiragana', front: 'み', back: 'mi' },
  { id: 'h-33', deckId: 'hiragana', front: 'む', back: 'mu' },
  { id: 'h-34', deckId: 'hiragana', front: 'め', back: 'me' },
  { id: 'h-35', deckId: 'hiragana', front: 'も', back: 'mo' },
  { id: 'h-36', deckId: 'hiragana', front: 'や', back: 'ya' },
  { id: 'h-37', deckId: 'hiragana', front: 'ゆ', back: 'yu' },
  { id: 'h-38', deckId: 'hiragana', front: 'よ', back: 'yo' },
  { id: 'h-39', deckId: 'hiragana', front: 'ら', back: 'ra' },
  { id: 'h-40', deckId: 'hiragana', front: 'り', back: 'ri' },
  { id: 'h-41', deckId: 'hiragana', front: 'る', back: 'ru' },
  { id: 'h-42', deckId: 'hiragana', front: 'れ', back: 're' },
  { id: 'h-43', deckId: 'hiragana', front: 'ろ', back: 'ro' },
  { id: 'h-44', deckId: 'hiragana', front: 'わ', back: 'wa' },
  { id: 'h-45', deckId: 'hiragana', front: 'を', back: 'wo' },
  { id: 'h-46', deckId: 'hiragana', front: 'ん', back: 'n' },

  // Katakana (46 cards)
  { id: 'k-1', deckId: 'katakana', front: 'ア', back: 'a' },
  { id: 'k-2', deckId: 'katakana', front: 'イ', back: 'i' },
  { id: 'k-3', deckId: 'katakana', front: 'ウ', back: 'u' },
  { id: 'k-4', deckId: 'katakana', front: 'エ', back: 'e' },
  { id: 'k-5', deckId: 'katakana', front: 'オ', back: 'o' },
  { id: 'k-6', deckId: 'katakana', front: 'カ', back: 'ka' },
  { id: 'k-7', deckId: 'katakana', front: 'キ', back: 'ki' },
  { id: 'k-8', deckId: 'katakana', front: 'ク', back: 'ku' },
  { id: 'k-9', deckId: 'katakana', front: 'ケ', back: 'ke' },
  { id: 'k-10', deckId: 'katakana', front: 'コ', back: 'ko' },
  { id: 'k-11', deckId: 'katakana', front: 'サ', back: 'sa' },
  { id: 'k-12', deckId: 'katakana', front: 'シ', back: 'shi' },
  { id: 'k-13', deckId: 'katakana', front: 'ス', back: 'su' },
  { id: 'k-14', deckId: 'katakana', front: 'セ', back: 'se' },
  { id: 'k-15', deckId: 'katakana', front: 'ソ', back: 'so' },
  { id: 'k-16', deckId: 'katakana', front: 'タ', back: 'ta' },
  { id: 'k-17', deckId: 'katakana', front: 'チ', back: 'chi' },
  { id: 'k-18', deckId: 'katakana', front: 'ツ', back: 'tsu' },
  { id: 'k-19', deckId: 'katakana', front: 'テ', back: 'te' },
  { id: 'k-20', deckId: 'katakana', front: 'ト', back: 'to' },
  { id: 'k-21', deckId: 'katakana', front: 'ナ', back: 'na' },
  { id: 'k-22', deckId: 'katakana', front: 'ニ', back: 'ni' },
  { id: 'k-23', deckId: 'katakana', front: 'ヌ', back: 'nu' },
  { id: 'k-24', deckId: 'katakana', front: 'ネ', back: 'ne' },
  { id: 'k-25', deckId: 'katakana', front: 'ノ', back: 'no' },
  { id: 'k-26', deckId: 'katakana', front: 'ハ', back: 'ha' },
  { id: 'k-27', deckId: 'katakana', front: 'ヒ', back: 'hi' },
  { id: 'k-28', deckId: 'katakana', front: 'フ', back: 'fu' },
  { id: 'k-29', deckId: 'katakana', front: 'ヘ', back: 'he' },
  { id: 'k-30', deckId: 'katakana', front: 'ホ', back: 'ho' },
  { id: 'k-31', deckId: 'katakana', front: 'マ', back: 'ma' },
  { id: 'k-32', deckId: 'katakana', front: 'ミ', back: 'mi' },
  { id: 'k-33', deckId: 'katakana', front: 'ム', back: 'mu' },
  { id: 'k-34', deckId: 'katakana', front: 'メ', back: 'me' },
  { id: 'k-35', deckId: 'katakana', front: 'モ', back: 'mo' },
  { id: 'k-36', deckId: 'katakana', front: 'ヤ', back: 'ya' },
  { id: 'k-37', deckId: 'katakana', front: 'ユ', back: 'yu' },
  { id: 'k-38', deckId: 'katakana', front: 'ヨ', back: 'yo' },
  { id: 'k-39', deckId: 'katakana', front: 'ラ', back: 'ra' },
  { id: 'k-40', deckId: 'katakana', front: 'リ', back: 'ri' },
  { id: 'k-41', deckId: 'katakana', front: 'ル', back: 'ru' },
  { id: 'k-42', deckId: 'katakana', front: 'レ', back: 're' },
  { id: 'k-43', deckId: 'katakana', front: 'ロ', back: 'ro' },
  { id: 'k-44', deckId: 'katakana', front: 'ワ', back: 'wa' },
  { id: 'k-45', deckId: 'katakana', front: 'ヲ', back: 'wo' },
  { id: 'k-46', deckId: 'katakana', front: 'ン', back: 'n' },

  // N5 Vocab (100 cards)
  { id: 'v-1', deckId: 'n5-vocab', front: '学校', back: 'School (gakkou)' },
  { id: 'v-2', deckId: 'n5-vocab', front: '先生', back: 'Teacher (sensei)' },
  { id: 'v-3', deckId: 'n5-vocab', front: '学生', back: 'Student (gakusei)' },
  { id: 'v-4', deckId: 'n5-vocab', front: '私', back: 'I, me (watashi)' },
  { id: 'v-5', deckId: 'n5-vocab', front: 'あなた', back: 'You (anata)' },
  { id: 'v-6', deckId: 'n5-vocab', front: '友達', back: 'Friend (tomodachi)' },
  { id: 'v-7', deckId: 'n5-vocab', front: '本', back: 'Book (hon)' },
  { id: 'v-8', deckId: 'n5-vocab', front: '机', back: 'Desk (tsukue)' },
  { id: 'v-9', deckId: 'n5-vocab', front: '椅子', back: 'Chair (isu)' },
  { id: 'v-10', deckId: 'n5-vocab', front: '犬', back: 'Dog (inu)' },
  { id: 'v-11', deckId: 'n5-vocab', front: '猫', back: 'Cat (neko)' },
  { id: 'v-12', deckId: 'n5-vocab', front: '食べる', back: 'To eat (taberu)' },
  { id: 'v-13', deckId: 'n5-vocab', front: '飲む', back: 'To drink (nomu)' },
  { id: 'v-14', deckId: 'n5-vocab', front: '見る', back: 'To see, to watch (miru)' },
  { id: 'v-15', deckId: 'n5-vocab', front: '聞く', back: 'To listen, to hear (kiku)' },
  { id: 'v-16', deckId: 'n5-vocab', front: '話す', back: 'To speak (hanasu)' },
  { id: 'v-17', deckId: 'n5-vocab', front: '行く', back: 'To go (iku)' },
  { id: 'v-18', deckId: 'n5-vocab', front: '来る', back: 'To come (kuru)' },
  { id: 'v-19', deckId: 'n5-vocab', front: '帰る', back: 'To return home (kaeru)' },
  { id: 'v-20', deckId: 'n5-vocab', front: '大きい', back: 'Big (ookii)' },
  { id: 'v-21', deckId: 'n5-vocab', front: '小さい', back: 'Small (chiisai)' },
  { id: 'v-22', deckId: 'n5-vocab', front: '高い', back: 'Tall, expensive (takai)' },
  { id: 'v-23', deckId: 'n5-vocab', front: '安い', back: 'Cheap (yasui)' },
  { id: 'v-24', deckId: 'n5-vocab', front: '新しい', back: 'New (atarashii)' },
  { id: 'v-25', deckId: 'n5-vocab', front: '古い', back: 'Old (furui)' },
  { id: 'v-26', deckId: 'n5-vocab', front: '良い', back: 'Good (ii/yoi)' },
  { id: 'v-27', deckId: 'n5-vocab', front: '悪い', back: 'Bad (warui)' },
  { id: 'v-28', deckId: 'n5-vocab', front: '今日', back: 'Today (kyou)' },
  { id: 'v-29', deckId: 'n5-vocab', front: '明日', back: 'Tomorrow (ashita)' },
  { id: 'v-30', deckId: 'n5-vocab', front: '昨日', back: 'Yesterday (kinou)' },
  { id: 'v-31', deckId: 'n5-vocab', front: '時間', back: 'Time (jikan)' },
  { id: 'v-32', deckId: 'n5-vocab', front: '今', back: 'Now (ima)' },
  { id: 'v-33', deckId: 'n5-vocab', front: '月曜日', back: 'Monday (getsuyoubi)' },
  { id: 'v-34', deckId: 'n5-vocab', front: '火曜日', back: 'Tuesday (kayoubi)' },
  { id: 'v-35', deckId: 'n5-vocab', front: '水曜日', back: 'Wednesday (suiyoubi)' },
  { id: 'v-36', deckId: 'n5-vocab', front: '木曜日', back: 'Thursday (mokuyoubi)' },
  { id: 'v-37', deckId: 'n5-vocab', front: '金曜日', back: 'Friday (kinyoubi)' },
  { id: 'v-38', deckId: 'n5-vocab', front: '土曜日', back: 'Saturday (doyoubi)' },
  { id: 'v-39', deckId: 'n5-vocab', front: '日曜日', back: 'Sunday (nichiyoubi)' },
  { id: 'v-40', deckId: 'n5-vocab', front: '一', back: 'One (ichi)' },
  { id: 'v-41', deckId: 'n5-vocab', front: '二', back: 'Two (ni)' },
  { id: 'v-42', deckId: 'n5-vocab', front: '三', back: 'Three (san)' },
  { id: 'v-43', deckId: 'n5-vocab', front: '四', back: 'Four (yon/shi)' },
  { id: 'v-44', deckId: 'n5-vocab', front: '五', back: 'Five (go)' },
  { id: 'v-45', deckId: 'n5-vocab', front: '六', back: 'Six (roku)' },
  { id: 'v-46', deckId: 'n5-vocab', front: '七', back: 'Seven (nana/shichi)' },
  { id: 'v-47', deckId: 'n5-vocab', front: '八', back: 'Eight (hachi)' },
  { id: 'v-48', deckId: 'n5-vocab', front: '九', back: 'Nine (kyuu/ku)' },
  { id: 'v-49', deckId: 'n5-vocab', front: '十', back: 'Ten (juu)' },
  { id: 'v-50', deckId: 'n5-vocab', front: '百', back: 'Hundred (hyaku)' },
  { id: 'v-51', deckId: 'n5-vocab', front: '千', back: 'Thousand (sen)' },
  { id: 'v-52', deckId: 'n5-vocab', front: '万', back: 'Ten thousand (man)' },
  { id: 'v-53', deckId: 'n5-vocab', front: '円', back: 'Yen (en)' },
  { id: 'v-54', deckId: 'n5-vocab', front: '人', back: 'Person (hito)' },
  { id: 'v-55', deckId: 'n5-vocab', front: '男', back: 'Man (otoko)' },
  { id: 'v-56', deckId: 'n5-vocab', front: '女', back: 'Woman (onna)' },
  { id: 'v-57', deckId: 'n5-vocab', front: '子', back: 'Child (ko)' },
  { id: 'v-58', deckId: 'n5-vocab', front: '家', back: 'House, home (ie, uchi)' },
  { id: 'v-59', deckId: 'n5-vocab', front: '車', back: 'Car (kuruma)' },
  { id: 'v-60', deckId: 'n5-vocab', front: '電気', back: 'Electricity, light (denki)' },
  { id: 'v-61', deckId: 'n5-vocab', front: '天気', back: 'Weather (tenki)' },
  { id: 'v-62', deckId: 'n5-vocab', front: '雨', back: 'Rain (ame)' },
  { id: 'v-63', deckId: 'n5-vocab', front: '雪', back: 'Snow (yuki)' },
  { id: 'v-64', deckId: 'n5-vocab', front: '電話', back: 'Telephone (denwa)' },
  { id: 'v-65', deckId: 'n5-vocab', front: '買う', back: 'To buy (kau)' },
  { id: 'v-66', deckId: 'n5-vocab', front: '売る', back: 'To sell (uru)' },
  { id: 'v-67', deckId: 'n5-vocab', front: '待つ', back: 'To wait (matsu)' },
  { id: 'v-68', deckId: 'n5-vocab', front: '持つ', back: 'To hold (motsu)' },
  { id: 'v-69', deckId: 'n5-vocab', front: '書く', back: 'To write (kaku)' },
  { id: 'v-70', deckId: 'n5-vocab', front: '読む', back: 'To read (yomu)' },
  { id: 'v-71', deckId: 'n5-vocab', front: '起きる', back: 'To get up (okiru)' },
  { id: 'v-72', deckId: 'n5-vocab', front: '寝る', back: 'To sleep (neru)' },
  { id: 'v-73', deckId: 'n5-vocab', front: '勉強する', back: 'To study (benkyou suru)' },
  { id: 'v-74', deckId: 'n5-vocab', front: '仕事する', back: 'To work (shigoto suru)' },
  { id: 'v-75', deckId: 'n5-vocab', front: 'はい', back: 'Yes (hai)' },
  { id: 'v-76', deckId: 'n5-vocab', front: 'いいえ', back: 'No (iie)' },
  { id: 'v-77', deckId: 'n5-vocab', front: 'これ', back: 'This (kore)' },
  { id: 'v-78', deckId: 'n5-vocab', front: 'それ', back: 'That (sore)' },
  { id: 'v-79', deckId: 'n5-vocab', front: 'あれ', back: 'That over there (are)' },
  { id: 'v-80', deckId: 'n5-vocab', front: 'どれ', back: 'Which one (dore)' },
  { id: 'v-81', deckId: 'n5-vocab', front: 'ここ', back: 'Here (koko)' },
  { id: 'v-82', deckId: 'n5-vocab', front: 'そこ', back: 'There (soko)' },
  { id: 'v-83', deckId: 'n5-vocab', front: 'あそこ', back: 'Over there (asoko)' },
  { id: 'v-84', deckId: 'n5-vocab', front: 'どこ', back: 'Where (doko)' },
  { id: 'v-85', deckId: 'n5-vocab', front: '誰', back: 'Who (dare)' },
  { id: 'v-86', deckId: 'n5-vocab', front: '何', back: 'What (nani/nan)' },
  { id: 'v-87', deckId: 'n5-vocab', front: 'いつ', back: 'When (itsu)' },
  { id: 'v-88', deckId: 'n5-vocab', front: 'どうして', back: 'Why (doushite)' },
  { id: 'v-89', deckId: 'n5-vocab', front: '上手', back: 'Skillful, good at (jouzu)' },
  { id: 'v-90', deckId: 'n5-vocab', front: '下手', back: 'Unskillful, bad at (heta)' },
  { id: 'v-91', deckId: 'n5-vocab', front: '好き', back: 'To like (suki)' },
  { id: 'v-92', deckId: 'n5-vocab', front: '嫌い', back: 'To dislike (kirai)' },
  { id: 'v-93', deckId: 'n5-vocab', front: '食べ物', back: 'Food (tabemono)' },
  { id: 'v-94', deckId: 'n5-vocab', front: '飲み物', back: 'Drink (nomimono)' },
  { id: 'v-95', deckId: 'n5-vocab', front: '映画', back: 'Movie (eiga)' },
  { id: 'v-96', deckId: 'n5-vocab', front: '音楽', back: 'Music (ongaku)' },
  { id: 'v-97', deckId: 'n5-vocab', front: 'スポーツ', back: 'Sports (supo-tsu)' },
  { id: 'v-98', deckId: 'n5-vocab', front: '店', back: 'Store, shop (mise)' },
  { id: 'v-99', deckId: 'n5-vocab', front: '駅', back: 'Station (eki)' },
  { id: 'v-100', deckId: 'n5-vocab', front: '飛行機', back: 'Airplane (hikouki)' },
];

export const grammarPoints: GrammarPoint[] = [
  {
    id: 'g-1',
    level: 'N5',
    title: 'AはBです (A wa B desu)',
    explanation: 'This is the most basic sentence structure in Japanese. It is used to state that "A is B". 「は」 (wa) is a topic particle, and 「です」 (desu) is a copula, similar to "is" or "am" or "are" in English.',
    examples: [
      { japanese: 'わたしはがくせいです。', english: 'I am a student. (Watashi wa gakusei desu.)' },
      { japanese: 'これはほんです。', english: 'This is a book. (Kore wa hon desu.)' },
    ],
  },
  {
    id: 'g-2',
    level: 'N5',
    title: 'Verb Conjugation (ます-form)',
    explanation: 'The ます (masu) form is the polite, non-past form of a verb. It is commonly used in daily conversation. To form it, you typically change the final "u" sound of the dictionary form verb to an "i" and add ます. For example, "kau" (to buy) becomes "kaimasu".',
    examples: [
      { japanese: 'わたしはほんをかいます。', english: 'I buy a book. (Watashi wa hon o kaimasu.)' },
      { japanese: 'かれはすしをたべます。', english: 'He eats sushi. (Kare wa sushi o tabemasu.)' },
    ],
  },
  {
    id: 'g-3',
    level: 'N5',
    title: 'Possessive Particle 「の」 (no)',
    explanation: 'The particle 「の」 (no) is used to show possession, similar to "apostrophe s" in English. It links two nouns, where the first noun possesses or describes the second noun.',
    examples: [
      { japanese: 'これはわたしのペンです。', english: 'This is my pen. (Kore wa watashi no pen desu.)' },
      { japanese: 'さくらさんのかばんは大きいです。', english: 'Sakura\'s bag is big. (Sakura-san no kaban wa ookii desu.)' },
    ],
  },
    {
    id: 'g-4',
    level: 'N5',
    title: 'Adjectives (い-Adjectives and な-Adjectives)',
    explanation: 'Japanese has two types of adjectives. い-adjectives end with い (like "ookii" - big). な-adjectives require な (na) when they come before a noun (like "kirei na hana" - beautiful flower).',
    examples: [
      { japanese: 'このラーメンはおいしいです。', english: 'This ramen is delicious. (Kono raamen wa oishii desu.)' },
      { japanese: 'しずかなへやがすきです。', english: 'I like quiet rooms. (Shizuka na heya ga suki desu.)' },
    ],
  },
  {
    id: 'g-5',
    level: 'N5',
    title: 'Question Particle 「か」 (ka)',
    explanation: 'To turn a statement into a question, you simply add the particle 「か」 (ka) to the end of the sentence. The word order does not change, and a question mark is usually not necessary in formal writing.',
    examples: [
      { japanese: 'これはペンですか。', english: 'Is this a pen? (Kore wa pen desu ka.)' },
      { japanese: 'さとうさんはせんせいですか。', english: 'Is Mr. Sato a teacher? (Satou-san wa sensei desu ka.)' },
    ],
  },
  {
    id: 'g-6',
    level: 'N5',
    title: 'Past Tense (ました/でした)',
    explanation: 'To talk about the past, verbs in ます-form change to ました (mashita). For nouns and な-adjectives, です (desu) becomes でした (deshita). For い-adjectives, the final い becomes かったです (katta desu).',
    examples: [
      { japanese: 'きのう、えいがをみました。', english: 'I watched a movie yesterday. (Kinou, eiga o mimashita.)' },
      { japanese: 'きのうはあつかったです。', english: 'It was hot yesterday. (Kinou wa atsukatta desu.)' },
    ],
  },
  {
    id: 'g-7',
    level: 'N4',
    title: 'Potential Form (~ことができます / ~れる/られる)',
    explanation: 'This form expresses ability ("can do something"). One way is to use "Dictionary Form Verb + ことができます". Another is to conjugate the verb itself. For る-verbs, change る to られる. For う-verbs, change the final "u" vowel to "e" and add る.',
    examples: [
      { japanese: 'わたしはかんじをよむことができます。', english: 'I can read Kanji. (Watashi wa kanji o yomu koto ga dekimasu.)' },
      { japanese: 'かれはすしがたべられます。', english: 'He can eat sushi. (Kare wa sushi ga taberaremasu.)' },
    ],
  },
  {
    id: 'g-8',
    level: 'N4',
    title: 'Conditional Form (~たら)',
    explanation: 'The 「たら」 (tara) form is a common way to express "if" or "when". It\'s formed by taking the past tense of a verb or adjective and adding 「ら」 (ra). It can be used for a wide range of conditional situations.',
    examples: [
      { japanese: 'にほんにいったら、さくらをみたいです。', english: 'If/When I go to Japan, I want to see the cherry blossoms. (Nihon ni ittara, sakura o mitai desu.)' },
      { japanese: 'やすかったら、かいます。', english: 'If it\'s cheap, I\'ll buy it. (Yasukattara, kaimasu.)' },
    ],
  },
  {
    id: 'g-9',
    level: 'N4',
    title: 'Giving and Receiving (あげる, くれる, もらう)',
    explanation: 'These verbs are crucial for social context. 「あげる」(ageru) is for giving to others. 「くれる」(kureru) is for someone giving to you or your in-group. 「もらう」(morau) is for receiving from others.',
    examples: [
      { japanese: 'わたしはともだちにはなをあげました。', english: 'I gave flowers to my friend. (Watashi wa tomodachi ni hana o agemashita.)' },
      { japanese: 'ともだちがわたしにはなをくれました。', english: 'My friend gave flowers to me. (Tomodachi ga watashi ni hana o kuremashita.)' },
      { japanese: 'わたしはともだちにはなをもらいました。', english: 'I received flowers from my friend. (Watashi wa tomodachi ni hana o moraimashita.)' },
    ],
  },
];

export const quizzes: QuizMeta[] = [
    {
        id: 'grammar-n5',
        type: 'grammar',
        title: 'N5 Grammar Quiz',
        description: 'Test your knowledge of N5 grammar points.',
        level: 'N5',
    },
    {
        id: 'grammar-n4',
        type: 'grammar',
        title: 'N4 Grammar Quiz',
        description: 'Test your knowledge of N4 grammar points.',
        level: 'N4',
    },
    {
        id: 'vocabulary-n5',
        type: 'vocabulary',
        title: 'N5 Vocabulary Quiz',
        description: 'A quiz on essential N5 flashcards.',
        level: 'N5',
    },
    {
        id: 'vocabulary-n4',
        type: 'vocabulary',
        title: 'N4 Vocabulary Quiz',
        description: 'A quiz on intermediate N4 flashcards.',
        level: 'N4',
    },
    {
        id: 'listening',
        type: 'listening',
        title: 'Listening Comprehension',
        description: 'Listen to a sentence and write what you hear.',
    },
    {
        id: 'creative-practice',
        type: 'creative-practice',
        title: 'Creative Practice',
        description: 'Test your skills by creating sentences that fit certain conditions, validated by AI.',
    }
];

export const listeningSentences: Omit<ListeningQuizQuestion, 'audioDataUri'>[] = [
    { id: 'l-1', kana: 'こんにちは', romaji: 'Konnichiwa' },
    { id: 'l-2', kana: 'ありがとうございます', romaji: 'Arigatou gozaimasu' },
    { id: 'l-3', kana: 'すみません', romaji: 'Sumimasen' },
    { id: 'l-4', kana: 'はい、そうです', romaji: 'Hai, sou desu' },
    {
      id: 'l-5',
      kana: 'これはいくらですか',
      romaji: 'Kore wa ikura desu ka',
    },
    { id: 'l-6', kana: 'えきはどこですか', romaji: 'Eki wa doko desu ka' },
    { id: 'l-7', kana: 'はじめまして', romaji: 'Hajimemashite' },
    {
      id: 'l-8',
      kana: 'どうぞよろしくおねがいします',
      romaji: 'Douzo yoroshiku onegaishimasu',
    },
    { id: 'l-9', kana: 'おなまえはなんですか', romaji: 'O-namae wa nan desu ka' },
    { id: 'l-10', kana: 'にほんごがすこしわかります', romaji: 'Nihongo ga sukoshi wakarimasu' },
];

export const creativeChallenges: CreativeChallenge[] = [
    { id: 'cc-1', conditions: ['Greetings', 'Politeness'] },
    { id: 'cc-2', conditions: ['Ask for price', 'A drink'] },
    { id: 'cc-3', conditions: ['Express gratitude', 'Receiving a gift'] },
    { id: 'cc-4', conditions: ['Introduce yourself', 'Mention your nationality'] },
    { id: 'cc-5', conditions: ['Ask for directions', 'Train station'] },
];
